### ISSUE TITLE
License Verification

### ISSUE THREAD

**Issue by vwalch** [accesio/APCI#13]
I don't see a LICENSE file in this repository, just in the apcilib.h file. Can you please verify they License of this project?

**Comment by jdolanIV** [comment]
ACCES is pretty much happy to share code under any license. The closest we have would be please use it with our hardware, but that's not something we would try to enforce in anyway.
We do produce code for customers that is closed source, but that involves advanced agreements.
If you have a project involving ACCES hardware and want to get it explicitly released to you under a specific license, then let us know.

**Comment by vwalch** [comment]
That's great, I appreciate you're so willing to work with developers. Without a license in your repository, I can't easily use it though. See this article: https://medium.com/glitch/why-add-a-license-to-your-open-source-project-6f07941f9288
Could you add a simple default permissive license like GPLv2 to match the Linux kernel in a LICENSE file? MIT and BSD would also work well.

**Comment by jdolanIV** [comment]
I will defer to @JHentges as he is the director of software, but I will say that I think the Medium article is completely wrong. If code is posted on GitHub public repositories without copyright statements it should be considered free to use. The author of the article even admits that this is the intention of most people posting to GitHub, and he describes himself as a developer turned evil marketer. I had once considered adding the wtfpl to our code http://www.wtfpl.net/ as it mostly captures my feelings about the licenses and permission culture.

**Comment by JHentges** [comment]
Hello, John Hentges here, Director of Software Engineering for ACCES I/O Products, Inc.
vwalch has your concern been handled? If you'd like I can slap an MIT license file in the repository, but we haven't actually found a license permissive enough for our tastes, nor one that supports hardware companies perfectly.
Feel free to use our Linux software and source in any way shape or form, with or without modification, with or without attribution, with or without giving us your code changes, without any limitation on commercial or other uses, AS IS, in perpetuity amen.  Please consider only using the code in relation to our hardware products. Enjoy!

**Comment by vwalch** [comment]
John,

Thank you for your response. We decided to just use it the way it is.

Valerie Walch
