### ISSUE TITLE
User space driver

### ISSUE THREAD

**Issue by ThibautLdn** [accesio/APCI#16]
Hi team,

Any chance there is a user space library (a .so file) ? This would simplify things to develop a python driver on my end

Kind regards

**Comment by ThibautLdn** [comment]
Hello,

Or is there a more complete documentation or an example of a script using this driver ?

Kind regards

**Comment by JHentges** [comment]
Hello, John Hentges here from ACCES.  Sorry for the delay in responding, apparently "respond directly to this email" didn't work.
In the apci/apcilib directory is the apcilib.c file which can be compiled into a .so.
Samples for various product families are located in the same directory.  What hardware are you using so I can point you in the direction of a specific source file?

**Comment by ThibautLdn** [comment]
Hello John
Ah yes indeed i missed that. I'm using a PCIe-ADIO16-16F

**Comment by JHentges** [comment]
I recommend the apci/apcilib/check.c and check_dma.c file.  Let me know if you have any questions -- or comments.  I'm here to help.
