### ISSUE TITLE
apcilib is missing isp-fpga.cpp

### ISSUE THREAD

**Issue by dberlin** [accesio/APCI#19]
The makefile for apcilib now has:

```isp_fpga: isp-fpga.cpp apcilib.h
	$(GCC) -o isp-fpga isp-fpga.cpp apcilib.c
```

However, isp-fpga.cpp was never added to the repository :)

**Comment by JHentges** [comment]
Added isp-fpga.cpp from eNET-AIO project.  Added important warning to source - READ before use.
