### ISSUE TITLE
Compilation broken since removal of GPL license tag

### ISSUE THREAD

**Issue by MaxPower2005** [accesio/APCI#22]
Since commit 1d6cd39293602 "modpost: turn missing MODULE_LICENSE() into error" the Linux kernel enforces that all modules have a valid MODULE_LICENSE tag.
Commit 2ec3361 removed this tag from apci_dev.c, causing compilation to fail on all "newer" kernel versions.

**Comment by JHentges** [comment]
Resolved: Added Dual MIT/GPL license tag
